Create startgame in air hockye class
Nitech-Jaeger/air-hockey pull request #31
Opened 2024-09-05 04:14 UTC by lasaqna

Closes []()

## 概要

ゲーム開始時に伴うパックやプレイヤーの初期化を行う関数を作成

## 変更内容

- 変更1
  - 説明が必要なら記述
- 変更2

## 変更内容の説明

1　bool型のメンバserverを追加
   -パックが左右どちら側でスポーンするのかを管理
2   パックの初期化
　-各サイドの中央にスポーンする。どちら側にスポーンするかはserverを参照
3   プレイヤーの初期化
　-画像処理クラスを呼び、手の位置情報とIDをリスト形式で獲得。
　‐左側はチームIDを０、右側はチームIDを１に設定
　‐プレイヤークラスのHAND_IDは手のIDと同じ

## 確認方法

# チェックリスト
- [ ] PRのタイトルを書いた
- [ ] File Changedで不要な変更や誤った変更が無いか確認した
- [ ] コミット名や内容は適切である
- [ ] 対応したissueをこのPRにリンクした
- [ ] PRの内容を書いた
- [ ] Reviwersを追加した
- [ ] Assigneesに自分を追加した
- [ ] 対応したissueをProjectの"Reviewing/Pending/Waiting for deploy"に移動した
- [ ] レビューを頼んだ人にDiscordでお願いした

2024-09-06 07:50 UTC, MurakawaTakuya requested changes
`bool型のメンバserverを追加`って変更内容の説明にあったけどどこだろう...?

2024-09-06 07:50 UTC, MurakawaTakuya commented on app/game/AirHockey.py
> +            self._players.append(player)
1. `=`とか`+-*/`の演算子の前後にはスペースを入れよう(なんか入ってたり入ってなかったりするから統一しよう)
2. `,`の後ろはスペースを入れよう

(`+=`とか`/=`はくっつけたままで大丈夫、離すとたしかエラーになる)

2024-09-06 07:51 UTC, MurakawaTakuya commented
@lasaqna 
https://github.com/Nitech-Jaeger/air-hockey/pull/31#pullrequestreview-2285256714

一旦この表記だけ直してもらって、追加であれば追ってレビューするわ～

2024-09-13 03:40 UTC, TANSUvsKOYUBI approved these changes

2024-09-23 07:22 UTC, merged